name: howbadismybatch-venv
channels:
  - defaults
  # - conda-forge
dependencies:
  - python=3.9
  - ipykernel
  - numpy
  - pandas
  - urllib3
  - requests
  - bs4
  - lxml
  - jupyter
  - tensorflow=2.11
  - nb_conda_kernels
  - pillow
  - openpyxl
  - tqdm
  - simplejson
  # - python-decouple
  # - selenium
  # - webdriver-manager
  # - pycountry
prefix: /home/frankknoll/anaconda3/envs/howbadismybatch-venv
